apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: CP Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: QA1
          artifact-id: f15e4be9-5d2e-423d-9823-7f69619f6072
          target-environment: QA-env
